src/iclient_persistence.cpp

malloc(3) is declared on stdlib.h header
Signed-off-by: Guilherme Maciel Ferreira <guilherme.maciel.ferreira@gmail.com>

Add missing header

---

src/ssl_options.cpp

When connecting with a SSL enabled server, the Paho client issues the
following errors:
SSL routines:SSL_CTX_use_certificate_chain_file:system lib:ssl_rsa.c:701
SSL routines:FILE_CTRL:system lib:bss_file.c:400
The error is caused because the SSLSocket_createContext() function
uses the MQTTClient_SSLOptions's members (keyStore, trustStore and
enabledCipherSuites) even if they are empty strings. The only way the
function doesn't use a particular member is setting it to NULL.
However, the ssl_options's constructors and assignment operators
initialize the members keyStore, trustStore and enabledCipherSuites
with empty strings (std::strings::c_str()).
So, despite setting only the trustStore, the user ends up passing
all members as valid, not NULL, strings. Then, SSLSocket_createContext()
calls …

Use the same semantic as Paho MQTT C for invalid strings

---

src/async_client.cpp
src/iclient_persistence.cpp
src/mqtt/token.h

Replace function-style casts (i.e. T(v)) and C-Style casts (i.e. (T)v) by named casts. This provides a better error checking and prevents conversion bugs.
Signed-off-by: Guilherme Maciel Ferreira guilherme.maciel.ferreira@gmail.com

Use named C++ casts instead of C-Style casts

---

src/client.cpp
src/mqtt/client.h

The member variable `timeout_` is `int` as well as the `set_time_to_wait()`. Thus there's no reason for the `get_time_to_wait()` to return a different type.

Fix get_time_to_wait() return type

---

src/mqtt/async_client.h
src/mqtt/client.h
src/mqtt/delivery_token.h
src/mqtt/iaction_listener.h
src/mqtt/iasync_client.h
src/mqtt/iclient_persistence.h
src/mqtt/ipersistable.h
src/mqtt/message.h
src/mqtt/response_options.h
src/mqtt/token.h
src/mqtt/topic.h

Rename, remove and add a parameter to match documentation and signature.
Fix some typos and misspellings. Fix errors reported by doxygen 1.8.3.

Fix Doxygen documentation

---

src/mqtt/exception.h

Fix exception message

---

src/iclient_persistence.cpp

The code uses named constants to indicate error. Like, for example `MQTTASYNC_PERSISTENCE_ERROR`. Then why not use the success constant `MQTTASYNC_SUCCESS`?
Signed-off-by: Guilherme Maciel Ferreira <guilherme.maciel.ferreira@gmail.com>

Return MQTTASYNC_SUCCESS instead of 0 to indicate success

---

src/connect_options.cpp
src/mqtt/token.h

Like the other options classes (`response_options`, `disconnect_options` and `delivery_response_options`), the `connect_options` initializes its token callback funtions instead of relying on `async_client` class to do it.

Class Connect Options initializes its own callback functions

---

src/mqtt/ssl_options.h
src/ssl_options.cpp

Prepare the `ssl_options` class to be tested. It adds an argument constructor and changes the semantics of the move constructor/assignment.

Prepare the ssl_options class to be tested

---

src/mqtt/topic.h
src/topic.cpp

This pull request has some commits that prepare the `topic `class to be tested. The basic idea here is to make the `topic `class as independent as possible, removing any tight coupling it might have.

Prepare the topic class to be tested

---

CMakeLists.txt

Replace the `LANGUAGES` directive, from the `project()` command, by the `enable_language()` command.

Reduce the required CMake version from 3.1 to 2.8.12

---

src/CMakeLists.txt

Fix issue  #67. 
Allow CMake to work with Paho MQTT C development builds. The headers and the library are not in standard directories, `${PAHO_MQTT_C_PATH}/include` and `${PAHO_MQTT_C_PATH}/lib`, respectively. Instead, in the Paho MQTT C development building, the headers are in `${PAHO_MQTT_C_PATH}/src` and the libraries are in `${PAHO_MQTT_C_PATH}/build/output`.
Tested with
- CMake version 2.8.12
- GNU GCC 4.8.2
Signed-off-by: Guilherme Maciel Ferreira <guilherme.maciel.ferreira@gmail.com>

CMake builds against Paho C development tree

---

src/mqtt/CMakeLists.txt

This is a bugfix for an issue that happens when invoking make install after using CMake to generate a Makefile. The existing CMakeLists configuration copies all header files to {INSTALL_DIR}/include, whereas the modified CMakeLists now copies the header files to {INSTALL_DIR}/include/mqtt, where they are expected by the source.
Steps to reproduce issue:
-Build paho.mqtt.cpp using CMake-generated makefile
-Install library invoking sudo make install
-Attempt to build a project that depends on the library and attempts to link the header files from {INSTALL_DIR}/include
Signed-off-by: Spencer Fowler <spencer@spencerfowler.com>

Update CMakeLists to install header files to correct directory

---

src/samples/CMakeLists.txt

Allow CMake to work with Paho MQTT C development builds. The Paho MQTT C headers are not in the standard `include` directory. Instead, in the Paho MQTT C development building, the headers are in `${PAHO_MQTT_C_PATH}/src`.
The library path is already resolved in `PAHO_MQTT_C_LIB` global variable.
Tested with
- CMake 3.4.1, 2.8.12
- GNU GCC 5.3.1

CMake builds "samples" against Paho C development tree

---

Makefile.am
src/connect_options.cpp
src/mqtt/connect_options.h
test/unit/ssl_options_test.h
test/unit/test.cpp

The Autotools' build was not passing the `OPENSSL` flag to the compiler. This was causing a lot of compilation and linking problems if the SSL support was disabled (`./configure --without-ssl`). For instance, in the samples:
```
$ ./configure --with-paho-mqtt-c=/tmp/paho-c/ --enable-samples --without-ssl
$ make
make[1]: Entering directory `/home/travis/build/guilhermeferreira/paho.mqtt.cpp/build_autotools'
CXX      src/libpaho_mqttpp3_la-async_client.lo
CXX      src/libpaho_mqttpp3_la-client.lo
CXX      src/libpaho_mqttpp3_la-disconnect_options.lo
CXX      src/libpaho_mqttpp3_la-iclient_persistence.lo
CXX      src/libpaho_mqttpp3_la-message.lo
CXX      src/libpaho_mqttpp3_la-response_options.lo
CXX      src/libpaho_mqttpp3_la-token.lo
CXX      src/libpaho_mqttpp3_la-topic.lo
CXX …
```

Fix the Autotools' compilation when SSL support is disabled

---

src/async_client.cpp
src/client.cpp
src/mqtt/async_client.h
src/mqtt/callback.h
src/mqtt/client.h
src/mqtt/delivery_token.h
src/mqtt/iaction_listener.h
src/mqtt/iasync_client.h
src/mqtt/token.h
src/mqtt/topic.h
src/samples/async_publish.cpp
src/samples/async_subscribe.cpp
src/samples/ssl_publish.cpp
src/samples/sync_publish.cpp
src/topic.cpp
test/unit/async_client_test.h
test/unit/dummy_action_listener.h
test/unit/dummy_async_client.h
test/unit/dummy_callback.h
test/unit/topic_test.h

This removes the token interfaces, `itoken` and `idelivery_token` and uses `token` and `delivery_token` objects directly in their place, mostly through shared pointers, `token_ptr` and `delivery_token_ptr`, respectively.
#83

Implementation of issue #83, remove the token interfaces

---

.gitignore
Makefile
test/unit/Makefile

This set of changes adds targets to the Makefile to execute unit tests and code coverage.

Add test and coverage targets to Makefile

---

.travis.yml

The script does the following:
- Install GCC 4.8, 4.9, 5.0 and 6.0.
- Install Clang 3.6 and 3.8.
- Install CppUnit for unit testing.
- Install Doxygen.
- Build the prerequisite (Paho MQTT C).
- Build the Paho MQTT C++ with GNU Make, CMake, and Autotools.
- Execute the Paho MQTT C++ test cases.

Travis: add CI script

---

.gitignore
.travis.yml
Makefile
install_paho_mqtt_c.sh

- Added an install script for Paho C lib
- Fixed GNU Make install and uninstall targets, and fixed .dep/.o file timestamp order
- Travis builds into default (not /tmp) directory

Travid building to default locations

---

appveyor.yml

This PR adds the [AppVeyor ](https://ci.appveyor.com), a continuous integration tool to test the build into Visual Studio. AppVeyor works like Travis but aims at Microsoft Windows. Indeed, this is a port from the Paho MQTT C, which already uses this tool to test their Windows build.
This version builds Paho MQTT C++ using CMake and Visual Studio 14.0 (2015).

Add AppVeyor - continuous integration for MS-Windows

---

src/client.cpp
src/message.cpp

From: https://en.cppreference.com/w/cpp/language/static
If a static data member is declared constexpr,
it is implicitly inline and does not need to be
redeclared at namespace scope. This redeclaration
without an initializer (formerly required)
is still permitted, but is deprecated.

Allow for usage in C++17 code.

---

src/mqtt/thread_queue.h

It was leading to wrong behavior on some target.

add missing return statement in thread_queue::try_put()

---

src/mqtt/exception.h

Signed-off-by: David Wagner <david.wagner@easymile.com>

Use MQTTAsync_strerror to provide meaningful error messages

---

README.md

Fix the minimum required version indicated on the install instructions
in the README.md file
Signed-off-by: Jose <joseespiriki@gmail.com>

Fix minimum required version of the Paho C lib

---

cmake/PahoMqttCppConfig.cmake.in

This could lead to CMake macros, find commands, etc. not working correctly, when package is included via find_package(PahoMqttCpp).
E.g. when `paho.mqtt.cpp` was built with `PAHO_WITH_SSL=True`, one should `set(PAHO_MQTT_SSL True)` before calling `find_package(PahoMqttCpp)`.

Fixed issue when build-time options were not written into configuration

---

cmake/PahoMqttCppConfig.cmake.in

The cmake configuration of a library should find all required dependencies, such that consumers can use the library without having to know about transient dependencies. This PR adds the required dependency `Threads` to the cmake config file.

Find required dependency Threads

---

.gitignore

This PR is concepted to include a new entry on .gitignore to exclude `/build/` folder created during building process out of the version control.

added /build/ folder to .gitignore

---

src/mqtt/client.h

In later C++ versions, std::async is marked nodiscard. See https://cplusplus.github.io/LWG/issue2856.
The code is correct in that it is properly blocking for the result, but it will now warn since this is considered "not the way".
Adding .wait() to the end of the calls, which explicitly waits on the future, should be the correct fix.
Fixes issue #340

Fix nodiscard warnings in sync client

---

src/connect_options.cpp
src/disconnect_options.cpp
test/unit/test_connect_options.cpp
test/unit/test_disconnect_options.cpp

ensures pointers to the properties are updated properly in move and copy constructors, so the c struct pointers remain valid
similar to #426, but I've also added tests and only try to set the structure if properties were provided (similar to SSL and will opts)

Fix copy/move constructor for connect/disconnect opts with properties

---

cmake/FindPahoMqttC.cmake

If a library is included that itself uses the Paho MQTT C++ it is not possible to add Paho MQTT C++ a second time. This results in the following message
`|   add_library cannot create imported target "PahoMqttC::PahoMqttC" because`
`|   another target with the same name already exists.`
It is not always possible to avoid such scenario (e.g. if third party software is used), so it is better to prevent this error.

avoid adding Paho MQTT C library twice

---

.gitmodules
CMakeLists.txt
cmake/FindPahoMqttC.cmake
src/CMakeLists.txt

Adding `paho.mqtt.c` as a submodule allows to use CMake `FetchContent` for dependency management. Furthermore, users can add `paho.mqtt.cpp` as a GIT submodule by calling CMake `add_subdirectory`. A CMake example for `FetchContent`:
```cmake
set(PAHO_BUILD_SHARED OFF)
set(PAHO_BUILD_STATIC ON)
set(PAHO_ENABLE_TESTING OFF)
set(PAHO_BUILD_TESTS OFF)
set(PAHO_WITH_MQTT_C ON)
FetchContent_Declare(
paho-mqttpp3-static
GIT_REPOSITORY https://github.com/HpLightcorner/paho.mqtt.cpp.git
GIT_TAG mqtt-c-submodule
)
FetchContent_MakeAvailable(paho-mqttpp3-static)
target_include_directories(${PROJECT_NAME} PRIVATE
${paho-mqttpp3-static_SOURCE_DIR}/src
)
target_link_libraries(${PROJECT_NAME} PRIVATE
paho-mqttpp3-static
)
```
The PR also includes changes proposed by #350 
Tested on Windows for static …

Add paho.mqtt.c as a submodule

---

src/mqtt/string_collection.h
test/unit/test_string_collection.cpp

This implements a simple iterator class on the `mqtt::string_collection` class. I wrote this for my own use as a convenience when working with string collections for logging from tokens, but thought it might be nice for other people too.
I only implemented a basic forward iterator, but there is nothing blocking making this a random access iterator: a forward iterator was all I needed.
This includes unit tests.

Iterable string collection

---

src/mqtt/token.h

I ran into a situation where I wanted to get the error message from the underlying C library (this is when the failure callback is called for connect).
The workaround I made was doing a `const_cast` on the token reference passed to the callback, and then calling `try_wait`, in order to trigger `check_ret`, which includes the error message in the exception it throws.
It would be nicer if you could just access the message on the token like you can for the reason code and return code.

add token::get_message

---

src/mqtt/CMakeLists.txt
src/mqtt/token.h

This PR add the missing `topic_matcher.h` header to the install target of the includes.
Note: the develop branch was behind the master, so I took the liberty of fork and make the change from master and not develop

build(include): add topic_matcher.h

---

cmake/PahoMqttCppConfig.cmake.in

When building with `PAHO_WITH_MQTT_C` and/or `PAHO_WITH_SSL`, the package config file doesn't correctly bring in these additional dependencies. This fixes that, so upstream projects pulling this in don't have to call `find_package` themselves on these dependencies.

export dependencies

---

src/mqtt/ssl_options.h

the original link leads `http://www.openssl.org/docs/apps/ciphers.html#CIPHER_LIST_FORMAT`  to "Page not found"

docs: update link for CIPHER LIST FORMAT

---

include/mqtt/async_client.h
include/mqtt/iasync_client.h
test/unit/test_async_client.cpp

This adds a function `consumer_events_available()` on the async client to get the number of events available for consumption. Similar to e558946c1dd664214505b48ca769024c781a53a6 I've added a default impl to the interface to avoid breaking old code which inherits from it.
The idea behind this is to allow exposing some stats in metrics, i.e. to see when consumers are lagging behind in consuming/processing messages, and the "pending" event count goes up. It may be also useful in some scenarios when implementing polling consumers, although I expect that in most cases the existing try_consume... functions are still more appropriate there.

Add function for checking async consumer event queue size

---

include/mqtt/ssl_options.h
src/ssl_options.cpp

On macOS I ran into this build error:
```
In file included from src/topic.cpp:19:
In file included from include/mqtt/topic.h:27:
In file included from /Users/laltenmueller/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:325:
In file included from /Users/laltenmueller/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_bool.h:19:
In file included from /Users/laltenmueller/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__format/formatter_integral.h:21:
In file included from /Users/laltenmueller/Downloads/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Develope …
```

Enable build with macOS STL

---

test/unit/test_async_client.cpp
test/unit/test_async_client_v3.cpp
test/unit/test_client.cpp

The Eclipse hosted MQTT public test broker that used to be at mqtt.eclipse.org has moved to mqtt.eclipseprojects.io.
See https://www.eclipse.org/lists/iot-wg/msg01733.html
Also adds missing `GOOD_SSL_SERVER_URI` when `TEST_EXTERNAL_SERVER` is set.

Update TEST_EXTERNAL_SERVER urls

---

include/mqtt/ssl_options.h
src/ssl_options.cpp

This change is needed to compile the library with clang/libc++ since version 19.
The library used `std::basic_string<unsigned char>` which requires `std::char_traits<unsigned char>` and is technically not defined by the standard. libc++ no longer supports it as of LLVM 19.

ssl_options: use std::vector<unsigned char> for the ALPN protocol list in wire format

---

src/topic.cpp
test/unit/test_topic.cpp

I'm using the filter in an object where it should start "uninitialized" until it is able to define its wildcard. In order to achieve that, I need an "unmatchable" topic. However ``topic_filter("")`` yields ``n=0``:
https://github.com/eclipse-paho/paho.mqtt.cpp/blob/17ff3dc0270738adc710667be44847eebc038ae0/src/topic.cpp#L108-L110 
leading to undefined behaviour on:
https://github.com/eclipse-paho/paho.mqtt.cpp/blob/17ff3dc0270738adc710667be44847eebc038ae0/src/topic.cpp#L121-L122 
This PR only leads to (negligible) cost increase to the case of matching shorter topics and longer topics with '#' wildcard:
https://github.com/eclipse-paho/paho.mqtt.cpp/blob/17ff3dc0270738adc710667be44847eebc038ae0/src/topic.cpp#L115-L123

Prevent undefined behavior empty topic matching
